export const MISSIONS: Record<number,string[]> = {
  6:["Dire à ta partenaire que tu es là pour elle","Faire les courses sans qu'elle ait à demander","Vérifier qu'un suivi médical est en place"],
  7:["Préparer des en-cas anti-nausées accessibles à tout moment","Éviter les odeurs fortes dans la maison","Commencer à lire sur la grossesse"],
  8:["Prendre le relais sur les tâches ménagères cette semaine","Accompagner ta partenaire à sa première consultation","Informer discrètement ton employeur si besoin"],
  9:["Pratiquer l'écoute active sans chercher à résoudre","Proposer un massage des pieds ou du dos le soir","Réduire les sources de stress dans la maison"],
  10:["Planifier la première échographie ensemble","Lire le guide accouchement","Préparer une liste de questions pour le médecin"],
  11:["Accompagner chercher des vêtements de grossesse si souhaité","Commencer à réfléchir à l'organisation financière","Déclarer la grossesse à la mutuelle"],
  12:["Être présent à l'échographie T1 : poser une demi-journée","Filmer et photographier l'échographie","Décider ensemble quand annoncer la grossesse"],
  13:["Annoncer la grossesse à la famille si vous le souhaitez","Commencer les discussions sur les prénoms","Lire le module post-partum pour anticiper"],
  14:["Organiser un week-end ou une sortie en amoureux","Commencer les recherches poussette et siège auto","Vérifier les aides financières et congés disponibles"],
  15:["Instaurer le rituel : parler à bébé chaque soir","Réserver les cours de préparation à l'accouchement","Commencer un album photo de la grossesse"],
  16:["Réserver les cours de préparation si pas encore fait","Établir la liste des achats prioritaires avec budget","Réfléchir à l'aménagement de la chambre"],
  17:["Instaurer le rituel de la main sur le ventre le soir","Commander le coussin de grossesse","Commencer le module valise maternité"],
  18:["Proposer des massages du dos réguliers","Préparer la chambre de bébé ensemble","Se renseigner sur les crèches de votre ville"],
  19:["Montage des meubles de la chambre de bébé","Établir la liste de naissance pour la famille","Initialiser les démarches de congé paternité"],
  20:["Bloquer la demi-journée pour l'échographie T2","Préparer les questions pour l'échographiste","Célébrer la mi-grossesse ensemble"],
  21:["Installer la veilleuse et vérifier l'éclairage","Commencer l'assemblage des meubles","Choisir la maternité définitivement"],
  22:["Instaurer le massage du ventre avec de l'huile le soir","Visiter la maternité et repérer les accès","Préparer le plan de naissance en brouillon"],
  23:["Prendre en charge toutes les corvées physiques lourdes","Préparer le sac de maternité","Lire intégralement le guide accouchement"],
  24:["Accompagner au test HGPO","Commencer la valise maternité","Installer le siège auto et faire vérifier le montage"],
  25:["Bain de pieds le soir, en faire un rituel","Finaliser la chambre de bébé","Finaliser le congé paternité avec l'employeur"],
  26:["Commander le coussin de grossesse si pas encore fait","Finaliser le plan de naissance par écrit","Préparer une playlist pour la salle de naissance"],
  27:["Remettre le plan de naissance à la maternité","Préparer les documents administratifs d'admission","Tester le trajet vers la maternité aux heures de pointe"],
  28:["Commencer la valise maternité maintenant","Vérifier le siège auto","Prendre connaissance du congé paternité"],
  29:["Apprendre la règle 5-1-1 pour l'accouchement","Finaliser la valise maternité","Vérifier que le téléphone est chargé en permanence"],
  30:["Planifier le congé paternité avec l'employeur","Finaliser les démarches administratives","Lire sur le post-partum"],
  31:["Proposer des promenades courtes régulièrement","Vérifier que la chambre est prête","Relire le guide accouchement"],
  32:["Accompagner à l'échographie T3","Vérifier le siège auto et le trajet maternité","Préparer des repas pour les premiers jours de retour"],
  33:["Être disponible la nuit si elle est réveillée","Finaliser tous les achats prioritaires","Préparer les contacts d'urgence"],
  34:["Vérifier que la valise est prête et dans la voiture","Mémoriser le numéro de la maternité","Rester joignable en permanence"],
  35:["Installer le siège auto maintenant","Faire vérifier l'installation du siège par un professionnel","Préparer la liste des personnes à appeler"],
  36:["Valise prête et dans la voiture","Téléphone chargé en permanence","Mémoriser le numéro direct des urgences obstétricales"],
  37:["Mode alerte active","Rester joignable en permanence","Réviser les signes du début du travail"],
  38:["Être présent, rassurant","Revoir ensemble le plan de naissance","Préparer des repas pour les premiers jours"],
  39:["Organiser une sortie douce","Rester patient","Préparer la maison pour le retour"],
  40:["Contractions toutes les 5 min, pendant 1 min, depuis 1h","Appeler la maternité avant de partir","Garder ton calme"],
  41:["Rester positif et patient","Suivre les instructions de l'équipe médicale","Être là, pleinement présent"],
};
